build:
  stage: build
  image: quay.io/buildah/stable:latest
  script:
    - buildah login --tls-verify=false -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - buildah bud --no-cache -t $CI_REGISTRY_IMAGE .
    - buildah push --tls-verify=false $CI_REGISTRY_IMAGE
  when: always

deploy-to-rancher:
  stage: deploy
  image: 
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    kubectl --kubeconfig $KUBECONFIG rollout undo deployment/restaurant-app -n restaurant

